limit derived queries to one year
censoredplanet/censoredplanet-analysis pull request #238
Opened 2023-05-31 15:19 UTC by ohnorobo

to reduce backend costs.

The costs of the hyperquack query goes from $34 -> 7

Currently this change breaks the e2e test (since it depends on reading the output of running the query, and has older data) But that's hard to fix since the e2e test runs in a particularly contrived way. I think it's okay in the short term.

Here are our pre-existing costs for a single day in dev when no one was using the dashboard (more analysis [here](https://docs.google.com/document/d/1ZVAlCS1RX6Kuq0p5S1wcwQ3s6qx0eN28_xYBUmjujA0/edit#heading=h.8r2orc94s0se))
![image](https://github.com/censoredplanet/censoredplanet-analysis/assets/1127209/7acca0c6-332c-4515-a1da-ff0e203ebe7b)

2023-05-31 15:55 UTC, fortuna commented on table/queries/derived_satellite_scans.sql
> +  WHERE date > DATE_SUB(CURRENT_DATE, INTERVAL 1 YEAR)
Perhaps with this? https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#declare

2023-05-31 15:56 UTC, fortuna commented on table/queries/derived_satellite_scans.sql
> +  WHERE date > DATE_SUB(CURRENT_DATE, INTERVAL 1 YEAR)
There's also https://cloud.google.com/bigquery/docs/reference/standard-sql/procedural-language#set

2023-06-01 13:42 UTC, fortuna commented on table/queries/merged_reduced_scans.sql
> +SET earliest_date = DATE_SUB(CURRENT_DATE, INTERVAL 1 YEAR);
Perhaps set it right after the declaration. Or use the default construct.

2023-06-01 13:46 UTC, ohnorobo commented on table/queries/merged_reduced_scans.sql
The idea is not to keep these long-term. We eventually want to move to appending queries (https://github.com/censoredplanet/censoredplanet-analysis/pull/218) which will be cheaper and allow us to process the full data.

2023-06-01 13:47 UTC, ohnorobo commented on table/queries/merged_reduced_scans.sql
> +  WHERE date > earliest_date
done

2023-06-01 13:52 UTC, fortuna approved these changes

2023-06-01 13:52 UTC, fortuna commented on table/queries/merged_reduced_scans.sql
In that case, can you add a comment to the variable that this is temporary and add a TODO to remove after the incremental pipeline?
Also explain what it does and why we need it. It will be helpful to explain why we don't have it for Satellite. Readers of this code will think there's something wrong with Satellite otherwise.

2023-06-01 13:56 UTC, ohnorobo commented
Added @ramakrishnansr, FYI

2023-06-02 13:44 UTC, ramakrishnansr commented on table/queries/merged_reduced_scans.sql
And even if these are short-term, I'd still prefer the restriction for Satellite. It would make it more clear if the same rule is applied across all datasets.

2023-06-05 19:55 UTC, ohnorobo commented on table/queries/merged_reduced_scans.sql
If the idea is to do this short term I would actually prefer to just remove the satellite query temporarily rather than limit it. That data doesn't even appear on the front end currently.

2023-06-05 20:24 UTC, fortuna commented
@ramakrishnansr your calculation is over-estimating the cost. With clustering you only see the real amount of data scanned after the query is done. The number shown in the editor is an upper-bound.

2023-06-05 20:36 UTC, fortuna requested changes

2023-06-05 20:36 UTC, fortuna commented on table/queries/merged_reduced_scans.sql
As we've discussed, I believe the better approach here is to remove the low-value domains, instead of data from high-value domains.

- Remove all the duplication. If there's example.com and www.example.com, keep only the canonical (i.e. the end of the redirection chain).
- Go over the [list of categories](https://github.com/citizenlab/test-lists/blob/master/lists/00-LEGEND-category_codes.csv) (36 of them), and specify a limit for each. For most categories, like porn or gambling, we don't need more than 10 domains. For others, like social media, we can have more. Pick the top based on popularity.
- Adjust the limits as need to ensure the data size we need.

A crude approach to validate would be to just take the top N by popularity.

We can also think of limiting the ASes. Perhaps we drop an AS if it's not in the top 5 from Cloudflare Radar and not in the top 95% of the county traffic as per the [APNIC ISP Market share](https://stats.labs.apnic.net/cgi-bin/aspop?c=IN).

That would apply to the public dashboard. The ACL's dashboard can use a separate table with all the data.

2023-06-06 12:17 UTC, merged

2023-06-06 12:17 UTC, ohnorobo commented
Merged to a side branch `prod-side`

2023-06-06 12:37 UTC, ohnorobo commented
I may also bump this to two years worth of data FYI. Will have to check the costs after a run.